name: Pull Requests

on:
  pull_request:
    branches:
      - master

jobs:
  runner:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      # Can maybe be replaced with pnpm/action-setup@v4 in the future
      - name: Setup pnpm/corepack
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
      - run: npm i -g --force corepack && corepack enable

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Setup PHP with tools
        uses: silverorange/actions-setup-php@v2
        with:
          php-version: '8.2'

      - name: Install PHP dependencies
        run: 'composer install'

      - name: Run tests
        timeout-minutes: 5
        run: |
          composer run phpcs:ci
          composer run phpstan:ci
          composer run phpunit
          pnpm prettier
